# Generated by Django 4.1.7 on 2023-03-31 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_registration_registrationform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationForm',
            new_name='Registration',
        ),
    ]
