# Generated by Django 4.1.7 on 2023-04-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=30)),
                ('Property', models.CharField(choices=[('F', 'Fields'), ('H', 'House'), ('G', 'Gold')], max_length=10)),
                ('document', models.FileField(upload_to='doc/')),
            ],
            options={
                'db_table': 'customer_table',
            },
        ),
    ]
