# Generated by Django 4.1.7 on 2023-04-01 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_pawnbroker_delete_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pawnbroker',
            table='pawnbroker_table',
        ),
    ]
