# Generated by Django 4.1.7 on 2023-04-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_pawnbroker_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pawnbroker',
            name='price',
        ),
        migrations.AlterField(
            model_name='pawnbroker',
            name='category',
            field=models.CharField(choices=[('House', 'Home'), ('Jewelry', 'Jewelry'), ('Electronics', 'Electronics'), ('Land', 'Land'), ('Others', 'Others')], max_length=100),
        ),
    ]
