# Generated by Django 4.1.7 on 2023-05-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_pawnbroker'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pawnbroker',
            table='pawnbroker_table',
        ),
    ]
