# Generated by Django 4.1.7 on 2023-05-06 15:46

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_pawnbroker_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'admin_table',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Others', 'Prefer not to say')], max_length=10)),
                ('dateofbirth', models.CharField(max_length=20)),
                ('salary', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('contact', models.BigIntegerField(unique=True)),
                ('registrationtime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_table',
            },
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.RenameField(
            model_name='pawnbroker',
            old_name='name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='pawnbroker',
            old_name='price',
            new_name='salary',
        ),
        migrations.RemoveField(
            model_name='pawnbroker',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pawnbroker',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pawnbroker',
            name='image',
        ),
        migrations.AddField(
            model_name='pawnbroker',
            name='contact',
            field=models.BigIntegerField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pawnbroker',
            name='dateofbirth',
            field=models.CharField(default=datetime.datetime(2023, 5, 6, 15, 45, 49, 227237), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pawnbroker',
            name='email',
            field=models.EmailField(default=datetime.datetime(2023, 5, 6, 15, 46, 7, 706920), max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pawnbroker',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Others', 'Prefer not to say')], default=datetime.datetime(2023, 5, 6, 15, 46, 14, 670293), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pawnbroker',
            name='location',
            field=models.CharField(default=datetime.datetime(2023, 5, 6, 15, 46, 23, 861904), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pawnbroker',
            name='password',
            field=models.CharField(default=datetime.datetime(2023, 5, 6, 15, 46, 33, 869651), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pawnbroker',
            name='registrationtime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pawnbroker',
            name='username',
            field=models.CharField(default=datetime.datetime(2023, 5, 6, 15, 46, 39, 452758), max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
