# Generated by Django 4.1.7 on 2023-05-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_admin_customer_delete_login_delete_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pawnbroker',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
