# Generated by Django 4.1.7 on 2023-05-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_pawnbroker_email_alter_pawnbroker_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PawnBroker',
            new_name='Pawnbrokers',
        ),
    ]
