# Generated by Django 4.1.7 on 2023-05-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_rename_pawnbroker_pawnbrokers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pawnbrokers',
            new_name='Pawnbroker',
        ),
        migrations.AlterModelTable(
            name='pawnbroker',
            table='pawnbroker_table',
        ),
    ]
