# Generated by Django 4.1.7 on 2023-05-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_rename_pawnbrokers_pawnbroker_alter_pawnbroker_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pawnbroker',
            name='gender',
        ),
    ]
