# Generated by Django 4.1.7 on 2023-05-06 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_pawnbroker_gender'),
    ]

    operations = [
    ]
